Update playwright project
ovartem/playwright_tests_with_po pull request #8
Opened 2024-07-14 12:08 UTC by EugenePetrik

Changes:
- update playwright dependency
-

2024-07-14 12:45 UTC, ovartem requested changes
2 small comments left. Thank you

2024-07-14 12:45 UTC, ovartem commented on .eslintrc.js
> +        'import/prefer-default-export': 'off' // TODO: remove
I think this should be removed, right?

2024-07-14 12:45 UTC, ovartem commented on src/fixtures/base.js
> +export const test = base.extend({
can you please setup JSDoc so that intellisense (codecomplition in tests) works for JS code?

2024-07-15 10:03 UTC, EugenePetrik commented on src/fixtures/base.js
> +export const test = base.extend({
Thanks for noticing, autocomplete is working now

<img width="518" alt="image" src="https://github.com/user-attachments/assets/46c5760b-6df5-4a1b-a71b-9dd7577fbdcb">

2024-07-15 10:13 UTC, ovartem approved these changes

2024-07-15 10:13 UTC, merged